// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';
export const MUSIC_ENABLE_LOADER = 'MUSIC_ENABLE_LOADER';
export const MUSIC_DISABLE_LOADER = 'MUSIC_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

//music list
export const MUSIC_LIST_REQUEST = 'MUSIC_LIST_REQUEST';
export const MUSIC_LIST_RESPONSE = 'MUSIC_LIST_RESPONSE';

// Fav List
export const FAVORITE_LIST_REQUEST = 'FAVORITE_LIST_REQUEST';
export const FAVORITE_LIST_RESPONSE = 'FAVORITE_LIST_RESPONSE';

// PlayList

export const UPDATE_PLAY_LIST = 'UPDATE_PLAY_LIST';
export const DELETE_PLAY_LIST = 'DELETE_PLAY_LIST';
export const DELETE_SONG_IN_PLAYLIST = 'DELETE_SONG_IN_PLAYLIST';

// Player
export const MUSIC_PLAYER_PAUSE = 'MUSIC_PLAYER_PAUSE';
export const MUSIC_PLAYER_PLAY = 'MUSIC_PLAYER_PLAY';
export const PLAYER_LIST_REQUEST = 'PLAYER_LIST_REQUEST';
export const PLAYER_LIST_RESPONSE = 'PLAYER_LIST_RESPONSE';

//plyer Flag
export const ISPLAYER_SHOWN = 'ISPLAYER_SHOWN';
